### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by deepdad** [Kostis-S-Z/trading-rl#1]
can you put your paper on GH please? on IEEE it's only available to institutions

**Comment by Kostis-S-Z** [comment]
Did you try the link in the README and didn't have access? It should work
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8683161

**Comment by Kostis-S-Z** [comment]
Uploaded paper (commit ebbdd798cd72dcf538dd9ddba28da8b9660bd07a)
