### ISSUE TITLE
Sample data sets

### ISSUE THREAD

**Issue by lamhk** [Kostis-S-Z/trading-rl#13]
Hi, do you have sample data sets on "train_data.npy" and "test_data.npy"?  Many thanks.

**Comment by mg64ve** [comment]
Hi @lamhk,

you can find a modified version of this repo at this Github URL:

https://github.com/q-learning/trading-rl

dataset is in data folder and it contains EURSD OHCL+Volume years 2007-2015.
Please let me know what you think about.
Thanks

**Comment by lamhk** [comment]
Thanks a lot.

**Comment by Kostis-S-Z** [comment]
Thank you @mg64ve. Closing.
