### ISSUE TITLE
Request For Paper : Price Trailing for Financial Trading Using Deep Reinforcement Learning

### ISSUE THREAD

**Issue by RaviKumarAndroid** [Kostis-S-Z/trading-rl#17]
https://ieeexplore.ieee.org/document/9112694
Can you provide a copy of your newly published paper to me 
my email is : kumarraviapp4u@gmail.com

Highly Appreciate your work.

Thanks

**Comment by RaviKumarAndroid** [comment]
i have been working on a paper of my own and i made some improvisations and changes upon the trailing reward. That why i would like to make some comparisons. Hope you can help
I Will Cite Both your papers

**Comment by Kostis-S-Z** [comment]
A link to the paper "Price Trailing for Financial Trading Using Deep Reinforcement Learning" can be found [here](https://github.com/Kostis-S-Z/Kostis-S-Z.github.io/blob/master/files/Price%20Trailing%20Regularized%20Deep%20Reinforcement%20Learning%20for%20Financial%20Trading.pdf)

**Comment by RaviKumarAndroid** [comment]
Thanks for adding it
