### ISSUE TITLE
File Directory error

### ISSUE THREAD

**Issue by e20916** [Kostis-S-Z/trading-rl#19]
I am trying the run the code. I use Tensorflow=1.14 and keras=2.3.1. But the code gives me error:

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'trailing//e:100_s:500_w:100_28.10_23:48'

I change the data directory according to read.me .The code generates new folders as trailing and deng. But after that it gives me this error. How can i solve this?

**Comment by Kostis-S-Z** [comment]
Hello @e20916 ,
Are you running this on Windows? The file path formats on windows are different than in Linux and that might be the cause.

Did you try changing the " / " to " \ " in the paths? e.g this line needs to be converted
`FOLDER = METHOD + "/e:" + ...`
to this
`FOLDER = METHOD + "\e:" + ... `
