### ISSUE TITLE
look ahead bias

### ISSUE THREAD

**Issue by mg64ve** [Kostis-S-Z/trading-rl#2]
Nice work, however I suspect there is a look ahead bias and I guess it is here:

```
            self.reward = self.get_reward()
            self.epoch_reward += self.reward

            self.position += 1
```

I think you should increment position before calculating reward.
What do you think about it?

**Comment by Kostis-S-Z** [comment]
Thank you for your comment. My first advice is to go over the paper carefully and this will, hopefully, clear any confusion.

Nonetheless, I will try to give a short answer by taking a **simplified** look at the sequence of some of the steps of the algorithm:
1. Based on equation (5), the agent at timestep _t_ decides for an action.
2. A reward is calculated as seen on equations (2) and (4) taking into account the position of the agent and the price at timestep _**t**_ and other variables (δ and commission fee)
3. At timestep _t+1_, the agent's position is incremented (with or without a change in direction (stay, go long / up, go short / down))

If the agent's position was incremented **before** the calculation of the reward, then in equation (2) you would have s_ _t+1_ instead of s_ _t_.

But, as I said, I highly recommend you go over the published paper uploaded in the repository as it contains everything you need to know in a much better and analytical way.

**Comment by mg64ve** [comment]
Thank you @Kostis-S-Z for your reply.
I have read your paper 3/4 times already and with pleasure because is well written, clear, concise but also with many details. I love this idea and the way you have studied and presented this work.
My concern it is not regarding the paper. What I am saying it seems to me there is a discrepancy between your paper and the code in this repo.
I hope you can follow what I am writing and reply clearly stating where I am wrong.
Before equation (5) you are writing:

> The neural network receives an input window
> composed of the l previous observation vectors. Each
> observation vector x(t) is defined as
> (5)

So I suppose these vectors are: x(t), x(t-1), x(t-2), ... x(t-l+1)
So the last element this vector contains p(t), s(t) and a(t-1).
Before equation (1) you are saying:

> After each time-step the agent must decide
> whether or not its position regarding the current price
> must be updated. Three possible actions are available:
> 1. stay at the previous level, i.e., s(t+1) = s(t) ,
> 2. follow an upward trend, i.e., s(t+1) = s(t) + s(t) · α, and
> 3. follow a downward trend, i.e., s(t+1) = s(t) − s(t) · α,

so since in your observation vector at time t you have s(t), I think that at time t you want to estimate s(t+1)..
Now having s(t) and the estimation of s(t+1) you can also infer the action a(t) to take.
At this stage, the consequence is that you can't use what is already in your observation vector to calculate the reward.
That's why I am saying that you need to increment self.position before calculating the reward.
In fact in your code you have:

```
    def input_s(self):
        """
        Prepare the input to the agent
        """
        input_up = (self.data[self.position] + self.margin) - self.value  # [0] - up values_std: ~0.0006
        input_down = self.value - (self.data[self.position] - self.margin)  # [2] - down

        if self.one_hot:
            # A very simple normalization so that the input values are all in the same range (with the one hot)
            input_up *= 1000
            input_down *= 1000

        observation = np.array([input_up, input_down])

        if self.one_hot:
            a = int(self.action == BUY)
            b = int(self.action == SELL)
            c = int(self.action != BUY and self.action != SELL)
            observation = np.append(observation, [a,b,c])

	return observation
```

This looks as the observation calculated at self.position
But when you call it in step function:

```
    def step(self, action):
        """
        OpenAI override function
        One step in Env includes: take action(move agent), store the action and
        the new value, get reward, get ready for next step(+1 position)
        return: the new state, reward and if the data are done
        """

        value = self.data[self.position]

        if action == 2:  # sell / short
            self.action = SELL
            self.value -= self.value * self.turn
            self.short_actions.append([self.position, value])
            self.prev_fin_pos = SELL
        elif action == 1:  # buy / long
            self.action = BUY
            self.value += self.value * self.turn
            self.long_actions.append([self.position, value])
            self.prev_fin_pos = BUY
        else:
            self.action = 0

        if (self.position + 1) < self.data_size:
            state = [self.position, value, self.action, self.value]
            self.memory.append(state)

            self.reward = self.get_reward()
            self.epoch_reward += self.reward

            self.position += 1
            if self.reset_margin:
                # if the agent gets out of boundaries reset him
                value = self.data[self.position]
                upper = value + self.margin
                lower = value - self.margin
                if (self.value > upper or self.value < lower):
                    self.value = value

            self.observation = self.input_s()
        else:
            self.done = True

	return self.observation, self.reward, self.done, {}
```

You call it at the end of the function. That means when step fuction is called again, it still have self.position value.
In my opinion, if want to calculate the reward you need to increment self.position value, before calculating it.
Because if you don't increment self.position, you calculate a reward on data you already have in your observation vector.

This is also a general practice with OpenAI Gym. If you read the following article from Adam King:

https://towardsdatascience.com/creating-a-custom-openai-gym-environment-for-stock-trading-be532be3910e

you see the step function is the following:

```
def step(self, action):
  # Execute one time step within the environment
  self._take_action(action)  

  self.current_step += 1  

  if self.current_step > len(self.df.loc[:, 'Open'].values) - 6:
    self.current_step = 0  delay_modifier = (self.current_step / MAX_STEPS)
  
  reward = self.balance * delay_modifier
  done = self.net_worth <= 0  
  obs = self._next_observation()  
  return obs, reward, done, {}
```
and the reason is quite the same: you already have data[self.current_step] in your observation, you don't nee to calculate the reward on that.

So in my opinion you should have to:

1. take an action a(t) based on observation vector containing data at time t
2. increment self.position
3. calculate the reward
4. get a new observation

I would highly appreciate if you can reply to my considerations and elaborating what is the weak point of my thoughts.
I hope this is not waste of time for you but a good time to consider and compare a different opinion.
Thanks you very much.
Kindly let me know.
Cheers.
