### ISSUE TITLE
discrepancy between paper and code

### ISSUE THREAD

**Issue by mg64ve** [Kostis-S-Z/trading-rl#3]
Dear @Kostis-S-Z ,
I have read your paper 3/4 times already and with pleasure because is well written, clear, concise but also with many details. I love this idea and the way you have studied and presented this work.
My concern it is not regarding the paper. I suspect there is a discrepancy between your paper and the code in this repo.
I hope you can follow what I am writing and reply clearly stating where I am wrong.
In the paper, before equation (5) you are writing:

> The neural network receives an input window
> composed of the l previous observation vectors. Each
> observation vector x(t) is defined as
> (5)

So I suppose these vectors are: x(t), x(t-1), x(t-2), ... x(t-l+1)
So the last element this vector contains p(t), s(t) and a(t-1).
Before equation (1) you are saying:

> After each time-step the agent must decide
> whether or not its position regarding the current price
> must be updated. Three possible actions are available:
> 1. stay at the previous level, i.e., s(t+1) = s(t) ,
> 2. follow an upward trend, i.e., s(t+1) = s(t) + s(t) · α, and
> 3. follow a downward trend, i.e., s(t+1) = s(t) − s(t) · α,

so since in your observation vector at time t you have s(t), I think that at time t you want to estimate s(t+1)..
Now having s(t) and the estimation of s(t+1) you can also infer the action a(t) to take.
At this stage, the consequence is that you can't use what is already in your observation vector to calculate the reward.
That's why I am saying that you need to increment self.position before calculating the reward.
In fact in your code you have:

```
    def input_s(self):
        """
        Prepare the input to the agent
        """
        input_up = (self.data[self.position] + self.margin) - self.value  # [0] - up values_std: ~0.0006
        input_down = self.value - (self.data[self.position] - self.margin)  # [2] - down

        if self.one_hot:
            # A very simple normalization so that the input values are all in the same range (with the one hot)
            input_up *= 1000
            input_down *= 1000

        observation = np.array([input_up, input_down])

        if self.one_hot:
            a = int(self.action == BUY)
            b = int(self.action == SELL)
            c = int(self.action != BUY and self.action != SELL)
            observation = np.append(observation, [a,b,c])

	return observation
```

This looks as the observation calculated at self.position
But when you call it in step function:

```
    def step(self, action):
        """
        OpenAI override function
        One step in Env includes: take action(move agent), store the action and
        the new value, get reward, get ready for next step(+1 position)
        return: the new state, reward and if the data are done
        """

        value = self.data[self.position]

        if action == 2:  # sell / short
            self.action = SELL
            self.value -= self.value * self.turn
            self.short_actions.append([self.position, value])
            self.prev_fin_pos = SELL
        elif action == 1:  # buy / long
            self.action = BUY
            self.value += self.value * self.turn
            self.long_actions.append([self.position, value])
            self.prev_fin_pos = BUY
        else:
            self.action = 0

        if (self.position + 1) < self.data_size:
            state = [self.position, value, self.action, self.value]
            self.memory.append(state)

            self.reward = self.get_reward()
            self.epoch_reward += self.reward

            self.position += 1
            if self.reset_margin:
                # if the agent gets out of boundaries reset him
                value = self.data[self.position]
                upper = value + self.margin
                lower = value - self.margin
                if (self.value > upper or self.value < lower):
                    self.value = value

            self.observation = self.input_s()
        else:
            self.done = True

	return self.observation, self.reward, self.done, {}
```

You call it at the end of the function. That means when step fuction is called again, it still have self.position value.
In my opinion, if want to calculate the reward you need to increment self.position value, before calculating it.
Because if you don't increment self.position, you calculate a reward on data you already have in your observation vector.

This is also a general practice with OpenAI Gym. If you read the following article from Adam King:

https://towardsdatascience.com/creating-a-custom-openai-gym-environment-for-stock-trading-be532be3910e

you see the step function is the following:

```
def step(self, action):
  # Execute one time step within the environment
  self._take_action(action)  

  self.current_step += 1  

  if self.current_step > len(self.df.loc[:, 'Open'].values) - 6:
    self.current_step = 0  delay_modifier = (self.current_step / MAX_STEPS)
  
  reward = self.balance * delay_modifier
  done = self.net_worth <= 0  
  obs = self._next_observation()  
  return obs, reward, done, {}
```
and the reason is quite the same: you already have data[self.current_step] in your observation, you don't need to calculate the reward on that.

So in my opinion you should have to:

1. take an action a(t) based on observation vector containing data at time t
2. increment self.position
3. calculate the reward
4. get a new observation

I would highly appreciate if you can reply to my considerations and elaborate what is the weak point of my thoughts.
I hope this is not waste of time for you but a good time to consider and compare a different opinion.
Thank you very much.
Kindly let me know.
Cheers.

**Comment by Kostis-S-Z** [comment]
Hi there,

Thanks again for the feedback and I appreciate the time you spent on reading carefully the paper and constructing a nice and clear issue! The code uploaded in this repo was an initial version we used, it has since seen many changes for the to be adapted in other settings and for the experiments for the paper, and unfortunately it doesn't follow the exact notation (variable names) of the paper.

It seems that your observation is correct, indeed the self.position attribute should be incremented before the reward, although this statement is not entirely correct.
> Because if you don't increment self.position, you calculate a reward on data you already have in your observation vector.

The reward of the agent is calculated based on the new agent value **_s(t+1)_** with respect to the new price value **_p(t+1)_**. Here, the new agent value _s(t+1)_ is calculated (which is different than the one in the observation vector) although in the reward function the _p(t)_ remains.
```
        if action == 2:  # sell / short
            self.action = SELL
            self.value -= self.value * self.turn  # s(t+1) = s(t) - s(t) * a
            self.short_actions.append([self.position, value])
            self.prev_fin_pos = SELL
        elif action == 1:  # buy / long
            self.action = BUY
            self.value += self.value * self.turn  # s(t+1) = s(t) + s(t) * a
            self.long_actions.append([self.position, value])
            self.prev_fin_pos = BUY
        else:
            self.action = NEUTRAL  # s(t+1) = s(t)
```

I uploaded the new code with additional comments and some better variable names for clarity. I am also planning in the next few months to add some real EUR-USD data to make the code more accessible and ready to experiment with. 

Cheers

**Comment by stevexxs** [comment]
Hi, @Kostis-S-Z 

`I am also planning in the next few months to add some real EUR-USD data to make the code more accessible and ready to experiment with.`
are you still planning to add some real data for the experiment ?

Thanks !

**Comment by Kostis-S-Z** [comment]
Hello @stevexxs ,

Sorry for the long wait but unfortunately I have multiple other projects I am working on and no longer have time to contribute to this project. If you have found any free data and have managed get it working with the code, ~~you could do a pull request and I would be very happy to review it!~~ fork the repo and add them to yours.

**Comment by stevexxs** [comment]
Hi @Kostis-S-Z 

@ScrapeWithYuri who raised issue #5, has already pushed data into his repo,
https://github.com/ScrapeWithYuri/trading-rl/tree/master/trading_agent/Data
according to #5, the period is 1h, but can easily change to 4h close price.

**Comment by mg64ve** [comment]
Hi @stevexxs and @ScrapeWithYuri,

Could please clarify what data is that?

**Comment by Kostis-S-Z** [comment]
> Hi @Kostis-S-Z
> 
> @ScrapeWithYuri who raised issue #5, has already pushed data into his repo,
> https://github.com/ScrapeWithYuri/trading-rl/tree/master/trading_agent/Data
> according to #5, the period is 1h, but can easily change to 4h close price.

Great, feel free to use them. But as @mg64ve it would be helpful to know the origin of the data. There are many sites where you can find exchange rate data but they might be missing values or a bit inconsistent if you are really keen on using it other than experimentation purposes.

I also decided **not** to add any data to this repo since it is a reference to a specific paper and not an ongoing project. It would be confusing to have different data in the repo than what it was used in the paper. But as I mention previously, feel free to fork it and use your own data.

**Comment by Kostis-S-Z** [comment]
Closing this for some clarity. If you want to talk about data or something else, feel free to create a new issue :)

This issue was fixed many months ago with the commit https://github.com/Kostis-S-Z/trading-rl/commit/3a4ab5714a28518308a226cb485a06b942a83095.

**Comment by personal-coding** [comment]
The data I grabbed was from https://www.finam.ru/profile/forex/eur-usd/export/?market=5&em=83&code=EURUSD. In the repo, I had pre-processed the data to exclude days where there was less than ~80 data points. Some days had few data points, which I wasn't sure was from missing data or shortened trading days.
