### ISSUE TITLE
Trade Actions

### ISSUE THREAD

**Issue by personal-coding** [Kostis-S-Z/trading-rl#6]
It appears the trade actions are using the t+1 close price instead of the current t close price. `values = values.reshape((-1,))` is pulling off the first data point, whereas actions is not `actions = np.array([x[2] for x in self.memory])`. I could not find in the article the exact method for the hypothetical trade actions. If a buy action is considered, is the model buying at t or t+1's close price? The current code appears to be t+1.

**Comment by Kostis-S-Z** [comment]
That is correct. The actions are for timestep _t+1_ of the closed price. You observe a value at time _t_ and then decide what action you should take next.

Edit 2: Some additional clarification: When you observe a value at timestep _**t**_ it is already in the past in the sense that the action and the trade you will perform will be executed at timestep _**t+1**_.

**Comment by Kostis-S-Z** [comment]
Closing the issue. Re-open it if i didn't answered your question
