### ISSUE TITLE
No data folder?

### ISSUE THREAD

**Issue by ghost** [Kostis-S-Z/trading-rl#7]
Hello,

  It seems there is no data folder?   Thanks!

**Comment by Kostis-S-Z** [comment]
Hello,

Indeed, I haven't uploaded a dataset to this repository. Some of the experiments contained copyrighted data and thus, unfortunately, it is not in my hands to publish them. Depending on the application you want (personal / commercial use) you need to find a dataset respectively. If you search online for "Euro-USD exchange rate dataset" you can find free / open datasets (e.g [here](https://sdw.ecb.europa.eu/quickview.do?SERIES_KEY=120.EXR.D.USD.EUR.SP00.A)), but bare in mind that they might not be of high quality.

**Comment by Kostis-S-Z** [comment]
Closing. Let me know if there is anything else I can do
